apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  # Generated Django secret key (base64 encoded)
  secret-key: aEo3Z0FrR1pPZWhOaVMxSDA4dF9JdERQQlctRjAwanA1UXJEN2wtWmdDUjI0dWpPQmxJeW9tZjVLZUFEUHRNU3lyWQ==
